apiVersion: apps/v1
kind: Deployment
metadata:
  name: schema-registry
  namespace: operators

spec:
  replicas: 1
  selector:
    matchLabels:
      app: schema-registry
  template:
    metadata:
      labels:
        app: schema-registry
    spec:
      enableServiceLinks: false
      containers:
        - name: schema-registry
          image: 10.97.40.42/cp-schema-registry:latest
          ports:
            - containerPort: 8081
          env:
            - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
              value: PLAINTEXT://kafka-cluster-kafka-bootstrap:9092
            - name: SCHEMA_REGISTRY_HOST_NAME
              value: schema-registry
            - name: SCHEMA_REGISTRY_LISTENERS
              value: http://0.0.0.0:8081

---
apiVersion: v1
kind: Service
metadata:
  name: schema-registry
  namespace: operators
spec:
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: schema-registry
