apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-cluster
  namespace: operators
  annotations:
    # strimzi.io/node-pools: enabled
    # strimzi.io/kraft: enabled
spec:
  kafka:
    version: 3.7.0
    replicas: 1
    storage: 
      type: ephemeral
    metadataVersion: 3.7.0-IV3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
  zookeeper:                # 👈 thêm phần này
    replicas: 1
    storage:
      type: ephemeral      
  entityOperator:
    topicOperator: {}
    userOperator: {}